FROM python:3.9.15-slim-bullseye

WORKDIR /code

COPY requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt 

COPY ./Fast API.py ./my-model2 /code/

EXPOSE 8000

CMD ["uvicorn", "hr_analytics_api:app", "--host", "0.0.0.0"]
