services:
  - type: web
    name: hr-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    workingDir: Backend
    autoDeploy: true

  - type: web
    name: hr-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlitapp.py --server.port=10001 --server.address=0.0.0.0
    workingDir: FrontEnd
    autoDeploy: true
