services:
  - type: web
    name: hr-backend
    env: python
    plan: free
    buildCommand: pip install -r Backend/requirements.txt
    startCommand: gunicorn main:app
    workingDir: Backend
    autoDeploy: true

  - type: web
    name: hr-frontend
    env: python
    plan: free
    buildCommand: pip install -r FrontEnd/requirements.txt
    startCommand: streamlit run streamlitapp.py --server.port=10000
    workingDir: FrontEnd
    autoDeploy: true
